window.FLOW_BOARD = {
  frames: [
    { id: "landing", lane: "entry", title: "Landing and login", status: "current", purpose: "Identify the participant and begin the journey.", entry: "Open demo", action: "Enter participant name", exit: "Domain selection", asset: "assets/current/01-landing.png" },
    { id: "domain", lane: "entry", title: "Domain selection", status: "current", purpose: "Choose the area to explore.", entry: "Login submitted", action: "Choose one domain", exit: "Intent selection", asset: "assets/current/02-domain.png" },
    { id: "intent", lane: "entry", title: "Intent selection", status: "current", purpose: "Choose whether to take stock, steady strain, or build forward.", entry: "Domain selected", action: "Choose one intent", exit: "Check-in questions", asset: "assets/current/03-intent.png" },
    { id: "question", lane: "entry", title: "Representative check-in question", status: "current", purpose: "Collect one response in the five-question sequence.", entry: "Intent selected", action: "Choose an answer or opt out", exit: "Next question or starting point", asset: "assets/current/04-question.png" },
    { id: "starting-point", lane: "entry", title: "Suggested starting point", status: "current", purpose: "Explain the suggested path without diagnostic framing.", entry: "Five questions completed", action: "Accept path or choose another area", exit: "Mentor selection", asset: "assets/current/05-starting-point.png" },
    { id: "mentor", lane: "setup", title: "Mentor selection", status: "current", purpose: "Choose the guide and archetype.", entry: "Path accepted", action: "Choose mentor", exit: "Voice selection", asset: "assets/current/06-mentor.png" },
    { id: "voice", lane: "setup", title: "Voice selection", status: "current", purpose: "Choose the mentor voice.", entry: "Mentor selected", action: "Preview and select voice", exit: "Tone selection", asset: "assets/current/07-voice.png" },
    { id: "tone", lane: "setup", title: "Tone selection", status: "current", purpose: "Choose the communication style.", entry: "Voice selected", action: "Choose tone", exit: "Journey introduction", asset: "assets/current/08-tone.png" },
    { id: "introduction", lane: "setup", title: "Journey introduction", status: "current", purpose: "Introduce the chosen guide and first message.", entry: "Tone selected", action: "Continue", exit: "Main dashboard", asset: "assets/current/09-introduction.png" },
    { id: "dashboard", lane: "daily", title: "Main dashboard", status: "current", purpose: "Show the active focus, mentor, activities, learning, and personal progress.", entry: "Setup completed or returning visit", action: "Choose activity, learning, or reflection", exit: "Selected daily-use state", asset: "assets/current/10-dashboard.png" },
    { id: "path", lane: "daily", title: "Path activity state", status: "current", purpose: "Complete one recommended practice.", entry: "Path activity selected", action: "Mark activity explored", exit: "Dashboard", asset: "assets/current/11-path.png" },
    { id: "constellation", lane: "daily", title: "Constellation learning state — unavailable", status: "unavailable", availability: "not-available", purpose: "Availability evidence: the component exists, but no current destination supplies learning data.", entry: "Not reachable in the current v2 demo", action: "No participant action available", exit: "Dashboard", asset: "assets/current/12-constellation.png" },
    { id: "reflection", lane: "daily", title: "Reflection or conversation", status: "current", purpose: "Name what the participant is noticing.", entry: "Conversation selected", action: "Submit reflection or return", exit: "Dashboard", asset: "assets/current/13-reflection.png" },
    { id: "dashboard-cohort", lane: "cohort", title: "Participant dashboard with cohort meter", status: "revised", purpose: "Add aggregate cohort progress to the existing dashboard.", entry: "Setup completed or returning visit", action: "Review contribution and open cohort progress", exit: "Shared cohort progress", asset: null },
    { id: "cohort-progress", lane: "cohort", title: "Shared cohort progress", status: "new", purpose: "Show aggregate weekly progress and milestones.", entry: "Cohort meter selected", action: "Review breadth, consistency, learning, and milestones", exit: "Dashboard", asset: null },
    { id: "program-summary", lane: "cohort", title: "Program aggregate summary", status: "new", purpose: "Show employer or school program engagement without personal data.", entry: "Program-owner access", action: "Review aggregate participation and content completion", exit: "Program navigation", asset: null },
  ],
  connectors: [
    { from: "landing", to: "domain", kind: "current" },
    { from: "domain", to: "intent", kind: "current" },
    { from: "intent", to: "question", kind: "current" },
    { from: "question", to: "starting-point", kind: "current" },
    { from: "starting-point", to: "mentor", kind: "current" },
    { from: "mentor", to: "voice", kind: "current" },
    { from: "voice", to: "tone", kind: "current" },
    { from: "tone", to: "introduction", kind: "current" },
    { from: "introduction", to: "dashboard", kind: "current" },
    { from: "dashboard", to: "path", kind: "current" },
    { from: "path", to: "dashboard", kind: "return" },
    { from: "dashboard", to: "constellation", kind: "unavailable", channel: 1 },
    { from: "constellation", to: "dashboard", kind: "unavailable" },
    { from: "dashboard", to: "reflection", kind: "current", channel: 0 },
    { from: "reflection", to: "dashboard", kind: "return" },
    { from: "dashboard", to: "dashboard-cohort", kind: "revision" },
    { from: "dashboard-cohort", to: "cohort-progress", kind: "proposed" },
  ],
};
